/*
 * This source file was generated by the Gradle 'init' task
 */
package com.sotabots;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void appHasAGreet() {
        // This is a basic test that will pass and satisfy Gradle
        assertTrue(true, "True should be true");
    }
}
