name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            label: Windows
          - os: ubuntu-latest
            label: Linux
          - os: macos-latest
            label: Mac
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean jpackageImage --no-configuration-cache

      - name: Zip output (Unix)
        if: runner.os != 'Windows'
        run: |
          DIR=$(find . -type d -name "jpackage" | head -1)
          cd "$DIR"
          zip -r ${{ github.workspace }}/${{ matrix.label }}-app.zip .
        shell: bash

      - name: Zip output (Windows)
        if: runner.os == 'Windows'
        run: |
          $dir = Get-ChildItem -Recurse -Directory -Filter "jpackage" | Select-Object -First 1 -ExpandProperty FullName
          Compress-Archive -Path "$dir\*" -DestinationPath "${{ matrix.label }}-app.zip"
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.label }}-app
          path: ${{ matrix.label }}-app.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          files: artifacts/**/*.zip
          body: |
            # SpeediWPILibTerminal
            ### What is this terminal thing?
            This is a terminal made to help FRC programmers quickly develop code.
            ### What am I solving?
            I, an experienced programmer of the SOTABots 2557 team, created this to help with the programming of the robot and of various tools. By using simple shortcuts on top of a shell, a programmer can quickly navigate, build, and deploy code.
            ### How do *I* use it?
            Download the .zip for your OS, extract it, and run the executable.
            Use the !help command to see what to do, or read the README for more extensive support.